SELECT * FROM customer;

-- 1. What is the total revenue generated by  by male vs female customers?

SELECT gender,SUM(purchase_amount) 
FROM customer
GROUP BY Gender;

-- 2. Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id,purchase_amount
FROM customer 
WHERE discount_applied = 'Yes' and purchase_amount>(SELECT AVG(purchase_amount) FROM customer);

-- 3. Which are the top 5 products with the hightest average review rating? 

SELECT item_purchased,AVG(review_rating) AS avg_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_product_rating DESC
LIMIT 5;

-- 4. Compare the average Purchase Amounts between Standard and Express Shipping.

SELECT shipping_type,AVG(purchase_amount)
FROM customer 
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;


-- 5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non subscribers.

SELECT subscription_status,
COUNT(customer_id) AS total_customers,
AVG(purchase_amount) AS average_spend,
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,average_spend DESC;

-- 6. Which 5 products have the hightest percentages of purchase with discount appiled ?

SELECT item_purchased,AVG(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100 AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- 7. Segment customers into New,Returning and loyal based their total number of previuos purchase and show the count of the each segment.

SELECT 
    customer_segment,
    COUNT(*) AS Number_of_Customers
FROM (
    SELECT 
        customer_id,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
) AS customer_type
GROUP BY customer_segment;

-- 8. What are the top 3 most purchased products within in each category ?

SELECT 
    category,
    item_purchased,
    total_purchases
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total_purchases,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(*) DESC
        ) AS rank_num
    FROM customer
    GROUP BY category, item_purchased
) AS ranked_products
WHERE rank_num <= 3;

-- 9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- 10. What is the revenue contribution of each age group? 

SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
